// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface Formato {
    idDepto: number;
    reporte: Reporte[];
}

export interface Reporte {
    nombre: string;
    codigo: string;
}
