// Generated by https://quicktype.io

export interface User {
    token:    string;
    ok:       boolean;
    id:       number;
    user:     string;
    userData: UserData;
}

export interface UserData {
    idUsuario:   number;
    usuario1:    string;
    descripcion: string;
    idNivel:     number;
    activo:      number;
    idDepto:     number;
    idPuesto:    number;
}
