name: Deploy Frontend a EC2

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Frontend Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: SSH y despliegue
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🚀 Frontend: pull, build & restart"
            cd /home/ec2-user/recibos-injuve
            git pull origin production
            npm install
            npm run build
            pm2 restart frontend || pm2 start frontend